spring:
  application:
    name: service-zuul
server:
  port: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client
  prefix: /v1