---
spring:
  profiles: peer1
server:
  port: 8761

eureka:
#  server:
#    renewalPercentThreshold: 0.49
  instance:
    hostname: peer1
  client:
#    fetchRegistry: false
#    registerWithEureka: false
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/

---
spring:
  profiles: peer2
server:
  port: 8762

eureka:
#  server:
#    renewalPercentThreshold: 0.49
  instance:
    hostname: peer2
  client:
#    fetchRegistry: false
#    registerWithEureka: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/